### ISSUE TITLE
Crash on start? 

### ISSUE THREAD

**Issue by Dracks** [CepiPerez/filecase-sailfish#2]
I tried installing filecase, and it crashes when start, with an empty blank screen. 

Opening from the terminal, I've got this stacktrace
```
[D] main:48 - Getting language from locale: "en_GB" 
[D] unknown:0 - Using Wayland-EGL
[W] unknown:39 - file:///usr/share/filecase/qml/filecase.qml:39:5: Type TransfersPage unavailable 
         TransfersPage { id: transfersPage }
         ^
[W] unknown:61 - file:///usr/share/filecase/qml/pages/TransfersPage.qml:61:19: Type TransfersDelegate unavailable 
             delegate: TransfersDelegate
                       ^
[W] unknown:145 - file:///usr/share/filecase/qml/pages/TransfersDelegate.qml:145:9: Cannot assign to non-existent property "_hasValueLabel" 
             _hasValueLabel: false
```

**Comment by CepiPerez** [comment]
Hello,

Please ask to flypig.
I don't have any sailfish device to test, I just uploaded his changes.

Regards

**Comment by Dracks** [comment]
Who is flypig? 

Thanks,

**Comment by llewelld** [comment]
> Who is flypig?

I'm flypig, but on github the name was already taken :(

**Comment by Dracks** [comment]
hi @llewelld, 

My device is an xperia XA2 with sailfish os X, (Fresh installation), Which data did you need? 

Thanks,

**Comment by llewelld** [comment]
Thanks for the offer of data, but I'm afraid this is a known problem of the version on OpenRepos for the XA2, since so far I only got around to updating the 64-bit rpms (for Xperia 10 II).

I can generate new rpms this evening for you which should fix the problem.

**Comment by llewelld** [comment]
@Dracks, I've published fresh rpms here: https://github.com/CepiPerez/filecase-sailfish/releases
I'd be grateful if you could test the appropriate one (armv7hl) on your device please.

**Comment by Dracks** [comment]
I think the rpm armv7hl is wrong:
```
 rpm -i filecase-0.2-1.armv7hl.rpm 
error: Failed dependencies:
	ld-linux-aarch64.so.1()(64bit) is needed by filecase-0.2-1.armv7hl
	ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) is needed by filecase-0.2-1.armv7hl
	libQt5Core.so.5()(64bit) is needed by filecase-0.2-1.armv7hl
```

**Comment by llewelld** [comment]
Yes, you're right it looks that way. Let me rebuild again after a full clean and see whether that fixes it.

**Comment by llewelld** [comment]
I've done a clean rebuild and uploaded a fresh rpm. The hash of the archive is different, so something inside it has changed. Hopefully it's something good. Would you mind please giving it another go.

**Comment by Dracks** [comment]
Now it's working.

I think dropbox is crashing,tomorrow i will take a look at the stacktrace



El Dimecres, 2 de juny 2021, David Llewellyn-Jones va escriure
> I've done a clean rebuild and uploaded a fresh rpm. The hash of the archive is different, so something inside it has changed. Hopefully it's something good. Would you mind please giving it another go.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/CepiPerez/filecase-sailfish/issues/2#issuecomment-85337345

-- 
Sent from my Sailfish device

**Comment by Dracks** [comment]
I created a ticket for the dropbox failing to start:
https://github.com/CepiPerez/filecase-sailfish/issues/4

And I close this ticket.
